basePath: /api
definitions:
  apperror.AppError:
    properties:
      code:
        type: string
      developer_message:
        type: string
      fields:
        $ref: '#/definitions/apperror.ErrorFields'
      message:
        type: string
      params:
        $ref: '#/definitions/apperror.ErrorParams'
    type: object
  apperror.ErrorFields:
    additionalProperties:
      type: string
    type: object
  apperror.ErrorParams:
    additionalProperties:
      type: string
    type: object
  entity.Operation:
    properties:
      category_uuid:
        type: string
      date_time:
        type: string
      description:
        type: string
      money_sum:
        type: number
      uuid:
        type: string
    type: object
  entity.Report:
    properties:
      operations:
        items:
          $ref: '#/definitions/entity.Operation'
        type: array
      total_money_sum:
        type: number
    type: object
host: localhost:10003
info:
  contact:
    email: ap363402@gmail.com
    name: Anton
  description: Statistics service for finance-manager application
  license:
    name: Apache 2.0
  title: Stats-service API
  version: "1.0"
paths:
  /metric:
    get:
      description: Checks that the server is up and running
      responses:
        "204":
          description: No Content
      summary: Heartbeat
      tags:
      - Heartbeat
  /operations:
    get:
      description: Retrieves a list of operations with support for filtering and sorting.
      parameters:
      - description: User UUID
        in: path
        name: user_uuid
        type: string
      - description: 'Category name (supports operators: substr)'
        in: path
        name: category_name
        type: string
      - description: Category type
        in: path
        name: type
        type: string
      - description: Category ID
        in: path
        name: category_id
        type: string
      - description: 'Description (supports operators: substr)'
        in: path
        name: description
        type: string
      - description: 'Money sum (supports operators: eq, neq, lt, lte, gt, gte, between)'
        in: path
        name: money_sum
        type: string
      - description: 'Date and time of operation (supports operators: eq, between;
          format: yyyy-mm-dd)'
        in: path
        name: date_time
        type: string
      - description: Field to sort by (money_sum, date_time, description)
        in: path
        name: sort_by
        type: string
      - description: Sort order (asc, desc)
        in: path
        name: sort_order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of operations
          schema:
            $ref: '#/definitions/entity.Report'
        "400":
          description: Validation error in filter or sort parameters
          schema:
            $ref: '#/definitions/apperror.AppError'
        "418":
          description: Something wrong with application logic
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Get operations
      tags:
      - Operations
swagger: "2.0"
